### ISSUE TITLE
idea for a stackableitems hack

### ISSUE THREAD

**Issue by booshican** [Flare-Client/Flare-Client#101]
i heard this is possible with some java clients and horion had this hack as well and since horion isnt being updated i was gonna ask if you could make it so you can stack items that normally cant be stacked like shulkers or armor

**Comment by EchoHackCmd** [comment]
I'll look into this!

**Comment by booshican** [comment]
thank you btw i mostly made this cause i used horion and had stackable shulkers in my e-chest and now i cant access them cause it wont let me
