### ISSUE TITLE
Repository contains an extremely large .pack file located in .git/objects/pack, increasing the repository size to 600MB

### ISSUE THREAD

**Issue by GrelTheL** [Flare-Client/Flare-Client#102]

**Comment by GrelTheL** [comment]
Solution: 
Step 1. Clone the repository locally
Step 2. Delete the .git folder entirely
Step 3. Delete the GitHub repository
Step 4. Make a new GitHub repository, and upload the files.
Step 5. Done.
I don't know what abomination you guys did to make this 600MB. No one is going to download 600MB for a 400kb project. Sorry guys.

**Comment by VriGamer25** [comment]
But there is not .git file in the main repository, is it in a specific folder? also the download size is coming to 300-400 KB when downloading.

**Comment by GrelTheL** [comment]
@VriGamer25 see attachment
![image](https://user-images.githubusercontent.com/59349394/79838416-533e3280-83f6-11ea-8993-8506f14e7e09.png)
.git is hidden by default, you can see it when you clone the repo.

**Comment by GrelTheL** [comment]
it works if you use the download zip button but not if you clone

**Comment by EchoHackCmd** [comment]
Just download the project instead of cloning..
