### ISSUE TITLE
Overlay doesn't appear in Fullscreen.

### ISSUE THREAD

**Issue by MysticD3AD** [Flare-Client/Flare-Client#110]
**The overlay does not appear in fullscreen since it is an overlay :/**

Have you ever considered hooking and doing an internal overlay?
If so, **why not**?

Might be a stupid question, but I am asking seriously!

"**Flare Client is a C# External Utility for Minecraft Bedrock Edition (Previously written in C++)**"

1 - Why did you switch to C#????????
2 - Why did you make it external?????????

**Comment by DisabledMallis** [comment]
It was never internal, which is why we switched because external C++ is a waste of effort & time.
Hooking and doing an internal overlay is much easier said than done.
