### ISSUE TITLE
Seeing coordinates of others.

### ISSUE THREAD

**Issue by VriGamer25** [Flare-Client/Flare-Client#114]
A feature named: Coordinates
What it will do: After putting a specific name VIA ClickGUI, and turning ON the feature, we can see the player's coordinates.

**Comment by Daxanius** [comment]
I guess it is possible to get the coordinates of the nearest player or something along those lines, but getting coordinates of other players wo are not in your render distance might not even be possible. I'm not sure myself.

**Comment by EchoHackCmd** [comment]
Only possible within the your players render distance
