### ISSUE TITLE
Creative mode not working

### ISSUE THREAD

**Issue by NoahTheFletcher** [Flare-Client/Flare-Client#116]
Creative mode does not allow user to obtain items in survival

**Comment by VriGamer25** [comment]
Please see the video in #announcements tab and see the pinned messages, thank you.

**Comment by NoahTheFletcher** [comment]
> Please see the video in #announcements tab and see the pinned messages, thank you.

Announcements tab? How do I navigate to this?

**Comment by DisabledMallis** [comment]
He is referring to our discord server, here is the link: https://discord.gg/Htd5rtb

**Comment by EchoHackCmd** [comment]
It's Client Sided
