### ISSUE TITLE
How do  I launch this

### ISSUE THREAD

**Issue by C-h-e-c-k-y** [Flare-Client/Flare-Client#123]
I cant find the thing to open to launch it help

**Comment by JoeThou** [comment]
Click releases then download flare-sharp.exe

**Comment by C-h-e-c-k-y** [comment]
Thx so much I waited so long lol

**Comment by SUPE4COOKIE** [comment]
compile it on visual studio

**Comment by cptgaming** [comment]
> compile it on visual studio

how do i do this?
