### ISSUE TITLE
Flare C# (Enhancement/Feature) - Near Warning

### ISSUE THREAD

**Issue by EchoHackCmd** [Flare-Client/Flare-Client#55]
Displays a floating window (Like the Click GUI Tabs) that renders both the closest players name and distance to help locate hidden players

**Comment by EchoHackCmd** [comment]
Is this ever going to be added??

**Comment by DisabledMallis** [comment]
1. We need to switch to DirectX before we start this (for performance reasons)
2. Why dont you do it
