### ISSUE TITLE
2020 New Updated ideas For Flare Client

### ISSUE THREAD

**Issue by SexFruit223** [Flare-Client/Flare-Client#61]
[Ideas_For_Client_Updates_-_SexFruit7407.txt](https://github.com/Flare-Client/Flare-Client/files/4177718/Ideas_For_Client_Updates_-_SexFruit7407.txt)

.view {Player_Name} to see their invetory

.echest gives u ur echest

.xp command {ammount of exp} so u can give urself some xp when needed to seem legit

.clear no-weather like so you don't need to see the rain?

.pe {Speed III 2:30} gives you PotionEffects without the current .give

.repair command to repair you're in hand tools, armor, etc. easily

.RepairAll repairs everything

.SafeWalk - Prevents from falling of blocks like for example in the nether

.hide Disguise hack change name so when you kill or get caught you just change your name so staff cant ban you

.feed feed yourself 

.regen regen your health

.invs invisible hack

.annoy {Player_Name} You can select a player and whatever they send in chat, you will repeat

.Fish Automatically pull's your rod back when a fish is caught

.AntiSlip Prevents you from slipping on ice to make it easier to walk on

.AntiBlind No Blindness

"Random Key" ParkourJump - Jump when reaching a block's edge

TrueSight/Truevision Show invisible enemies

"V" CameraNoClip - Let the camera in 3rd person go into walls over and under

.hj Horsejump- Automatically jump a horse at maximum height

.gpc Get Players Cords

.we Custom builds to copy and paste Kinda like world edit

**Comment by EchoHackCmd** [comment]
Most of these aren't possible unless you go internal
