### ISSUE TITLE
Hotkey as numbers?

### ISSUE THREAD

**Issue by VriGamer25** [Flare-Client/Flare-Client#69]
I don't know if this is a feature or bug, but whenever I select a keybind/hotkey for a feature, it shows a random number like 77.. or 65 instead of a letter.

**Comment by DisabledMallis** [comment]
this was done to help better compatability with minecraft's internal key down values. While they can be converted to chars, theyll display weird as a ! or smth when its a non letter, not as user friendly in my opinion.
