### ISSUE TITLE
Support Minecraft China

### ISSUE THREAD

**Issue by Liupaperbox** [Flare-Client/Flare-Client#81]
Is there any possibility to support the Chinese version based on Bedrock Edition? It is modified in the international version so it does not require ApplicationFrameHost.

**Comment by EchoHackCmd** [comment]
Are you sure that’s not just a fake version of the game?

**Comment by DisabledMallis** [comment]
> Are you sure that’s not just a fake version of the game?
Believe it or not its an actual thing.

As for if we can port it, we'll need a copy

**Comment by EchoHackCmd** [comment]
It sounds like an utter waste of time working on two separate copies of the game so we are most likely not going to work on the apparent Chinese version of the game. Thanks for the suggestion though.

**Comment by Liupaperbox** [comment]
Thank you, and I will work for it.
