### ISSUE TITLE
Realms bug

### ISSUE THREAD

**Issue by NYPDK** [Flare-Client/Flare-Client#82]
I'm Koreans in the discord, one of the support people.

I have seen twice now a strange bug people are having in realms where certain modules such as gamemode, jetpack, and others are not working. This only happens it specific realms and is temporary. When They test the modules in another realm or server everything seems to work fine.

**Comment by DisabledMallis** [comment]
this isnt a realm-specific issue - in fact im pretty sure it was already fixed in the code, but not actually published in a release yet. Ill leave this open until I can confirm that it is the case.
