### ISSUE TITLE
Request to add AutoFish

### ISSUE THREAD

**Issue by vic197** [Flare-Client/Flare-Client#83]
Title is self explanatory. Just putting it out there to have autofish added

**Comment by Armagann** [comment]
+1

**Comment by EchoHackCmd** [comment]
I don't think it's possible to implement this without going Internal

**Comment by DisabledMallis** [comment]
Re opening because the address for triggerbot oddly interacts with other stuff sometimes so we might be able to use that to cast the line, might not be possible though, just an idea.

**Comment by EchoHackCmd** [comment]
I added a new label to this!
