### ISSUE TITLE
Flare client crash

### ISSUE THREAD

**Issue by Dauntingnut2** [Flare-Client/Flare-Client#85]
There seems to be an issue to where after you use the client for a while it will stop working and when you try to use it it just crashes your game completely, also it only seems to effect that specific world regardless of whether or not you reinstall the client or delete the flare data folder

**Comment by Dauntingnut2** [comment]
Ok I seem to have narrowed it down a little, majority of the main crash seems to stem from either using it in the nether or using it during the transitions load screen into the nether/overworld

**Comment by EchoHackCmd** [comment]
Could you present me with a list of modules that you have enabled? This will probably narrow down the problem, also make sure you’re on Minecraft V1.14.3

**Comment by Dauntingnut2** [comment]
Air jump, no fall, tab GUI, module list and jetpack on a hot key

**Comment by EchoHackCmd** [comment]
This is weird, I'll label this issue as a bug so we can look further into this
