### ISSUE TITLE
Experiencing Consistent Bug in Realms

### ISSUE THREAD

**Issue by Fortuosity** [Flare-Client/Flare-Client#86]
Minecraft Version: Bedrock (Windows 10) v.1.14.30
Flare Version: Latest from Discord (v.0.0.6.4)
Bug Description: 
Flare works as normal on survival, and worked normally on Realms this morning (3/30).
However, as of this afternoon, some specific hacks (Flight, NoPacket, Gamemode) no longer function.
Of these, I am sure that Flight worked this morning. Attempting to run the client with only ClickGUI and flight on still resulted in a crash on Realms.
Any help with this would be greatly appreciated.

**Comment by EchoHackCmd** [comment]
are you on a BETA?

**Comment by Fortuosity** [comment]
No, I don't believe I am on a beta.

**Comment by EchoHackCmd** [comment]
What version are you on?
also a list of your enabled modules would be useful

**Comment by Fortuosity** [comment]
I'm not sure what happened, but flight seems to work for me now. Must have been an issue on my side. Thanks for your response!
