### ISSUE TITLE
request for a give or enchant feature

### ISSUE THREAD

**Issue by booshican** [Flare-Client/Flare-Client#96]
i know this is possible but i dont know how to do but i know that hack clients like horion that are bedrock hack clients can make it so you can give yourself items regardless of if you can use commands and same for enchanting but you can enchant beyond normal levels, it seems like a lot and i know you probably wont add it but it would still be a nice idea if you want to appeal a group of people who want clients that can give 32k items.

**Comment by EchoHackCmd** [comment]
That isn't possible unless we were to go Internal but we'd have to rewrite the entire Client and it'll be a pain to update

**Comment by booshican** [comment]
alright then just wanted to ask and also ask about a tp

**Comment by EchoHackCmd** [comment]
Flare already teleports the Player in some modules such as Freecam, TickedGlide & some others. We just don't have a UI that allows the Player to teleport to a specific set of Coordinates
