### ISSUE TITLE
NoKnockback and NoPacket crash error!

### ISSUE THREAD

**Issue by VriGamer25** [Flare-Client/Flare-Client#99]
Whenever turning on NoKnockback and NoPacket after some times, it crashes the game (Beta release).

**Comment by EchoHackCmd** [comment]
are you on v1.14.6? if so I will definitely look further into this

**Comment by VriGamer25** [comment]
Yeah, I am on 1.14.6 xd with Flare 0.0.7.1

**Comment by EchoHackCmd** [comment]
Fixed in v0.0.7.1
